# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cyril/workspace/eblearn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cyril/workspace/eblearn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Only default component available"
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cyril/workspace/eblearn/CMakeFiles /home/cyril/workspace/eblearn/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cyril/workspace/eblearn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named eblearn

# Build rule for target.
eblearn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eblearn
.PHONY : eblearn

# fast build rule for target.
eblearn/fast:
	$(MAKE) -f libeblearn/CMakeFiles/eblearn.dir/build.make libeblearn/CMakeFiles/eblearn.dir/build
.PHONY : eblearn/fast

#=============================================================================
# Target rules for targets named eblearn_gui

# Build rule for target.
eblearn_gui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eblearn_gui
.PHONY : eblearn_gui

# fast build rule for target.
eblearn_gui/fast:
	$(MAKE) -f eblearn/gui/CMakeFiles/eblearn_gui.dir/build.make eblearn/gui/CMakeFiles/eblearn_gui.dir/build
.PHONY : eblearn_gui/fast

#=============================================================================
# Target rules for targets named eblearn_tools

# Build rule for target.
eblearn_tools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eblearn_tools
.PHONY : eblearn_tools

# fast build rule for target.
eblearn_tools/fast:
	$(MAKE) -f eblearn/tools/CMakeFiles/eblearn_tools.dir/build.make eblearn/tools/CMakeFiles/eblearn_tools.dir/build
.PHONY : eblearn_tools/fast

#=============================================================================
# Target rules for targets named eblearn_tester

# Build rule for target.
eblearn_tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eblearn_tester
.PHONY : eblearn_tester

# fast build rule for target.
eblearn_tester/fast:
	$(MAKE) -f eblearn/tester/CMakeFiles/eblearn_tester.dir/build.make eblearn/tester/CMakeFiles/eblearn_tester.dir/build
.PHONY : eblearn_tester/fast

#=============================================================================
# Target rules for targets named facenet

# Build rule for target.
facenet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 facenet
.PHONY : facenet

# fast build rule for target.
facenet/fast:
	$(MAKE) -f eblearn/demos/facenet/CMakeFiles/facenet.dir/build.make eblearn/demos/facenet/CMakeFiles/facenet.dir/build
.PHONY : facenet/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... eblearn"
	@echo "... eblearn_gui"
	@echo "... eblearn_tools"
	@echo "... eblearn_tester"
	@echo "... facenet"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

