(setq gud-gdb-command-name "gdb --annotate=3 bin/eblearn_tester ")
(command-execute 'gdb)
(setq gdb-many-windows t)
(setq compile-command "cd .. && make debug")
(print "*** Debugging eblearn_tester with emacs and gdb.***")
(print "type \"r -nocolor\" to start debugging eblearn_tester")