release:
	cd build/Release && cmake -DCMAKE_BUILD_TYPE=Release ../.. && make all && cd ../..
debug:
	cd build/Debug && cmake -DCMAKE_BUILD_TYPE=Debug ../.. && make all && cd ../..
clean:
	rm -rf build/Debug/*
	rm -rf build/Release/*
	rm -rf bin/*
all:release
