ifndef (prj)
prj := all
endif

release:
	@echo __________________________________________________________________
	@echo "Compiling ${prj} project(s) in release mode..."
	@echo "Use 'make prj=idxgui' for example to compile a specific project."
	@echo __________________________________________________________________
	cd build/Release && cmake -DCMAKE_BUILD_TYPE=Release ../.. && make ${prj} && cd ../..
debug:
	@echo __________________________________________________________________
	@echo "Compiling ${prj} project in debug mode..."
	@echo "Use make debug prj=idxgui to compile a specific project."
	@echo __________________________________________________________________
	cd build/Debug && cmake -DCMAKE_BUILD_TYPE=Debug ../.. && make ${prj} && cd ../..
clean:
	rm -rf build/Debug/*
	rm -rf build/Release/*
	rm -rf bin/*
all:release
